<a href="https://colab.research.google.com/github/junaidfazam/Data-Analysis/blob/main/Numpy_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy for Data Analysis

#####Import Numpy

In [1]:
import numpy as np

#### Creating Numpy Arrays

#####From List

In [ ]:
#From List
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

a1 = np.array(list1, dtype='float')
a2 = np.array([list1,list2])# list of list 2D array

print(a1)
print(a2.shape)

[1. 2. 3. 4. 5.]
(2, 5)


#####From Range and Random Number

In [ ]:
np.arange(10,21)
np.arange(10,21,2)
np.arange(10,21,2).reshape(2,3) # reshaped in mxn array if there are 2*3 items

np.random.random((3,4)) # Item betweem 0-1

array([[0.21820719, 0.18155479, 0.84026432, 0.32304918],
       [0.86828293, 0.4621643 , 0.10716383, 0.35233273],
       [0.60077538, 0.3086044 , 0.00639313, 0.73354665]])

##### from fixed item


In [ ]:
np.arange(9)
np.arange(12).reshape(4,3) #only if 4*3=12

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#####Ones,Zeros and Indentity

In [ ]:
np.ones((3,4))
np.zeros((4,3))
np.identity(3) # 4 diagonal 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### Linearly spaced

In [ ]:
# used as axis in graph
a=np.linspace(-10,10,5, dtype=int) # 5 linearly spaced item
print(a)

[-10  -5   0   5  10]


#### Attribute

In [ ]:
a2.ndim # dimension of a2 array


2

In [ ]:
a2.shape # rows and columns

(2, 5)

In [ ]:
a2.size # total Items

10

In [ ]:
a1.dtype # data type of items

dtype('float64')

In [ ]:
a1.itemsize # size occupied in memory

8

####Changing Datatype

In [ ]:
a1.astype(float)

array([1., 2., 3., 4., 5.])

####Reshaping

In [ ]:
np.arange(12)
np.arange(12).reshape(3,4) # 3 rows and 4 colum
np.arange(12).reshape(3,4).ravel() # 1D

np.arange(12).reshape(3,4).T # 4 rows and 3 column
np.arange(12).reshape(3,4).T.ravel() # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

####Vectorized Operations

In [ ]:
a=np.arange(12).reshape(3,4)
a+10 # 10 added to each item
a>5 # boolean o/p
# a[a>5] # Filter the array with value greater than 5


array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

####Array Functions

In [ ]:
a =np.arange(12).reshape(3,4)

np.sum(a, axis=0) # Coloumn wise sum
np.sum(a, axis=1) # Row wise sum
np.mean(a, axis=1) # rows wise mean
np.mean(a, axis=1) # rows wise mean

np.cos(a)
np.log(a+1)
np.exp(a)

a1 =np.arange(6).reshape(2,3)
a2 =np.arange(6).reshape(3,2)
a1.dot(a2)


np.round(a+0.6)#Round/floor/ceil
np.floor(a+.6)
np.ceil(a+0.6)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

####Iterating

In [ ]:
a1 =np.arange(12)
a2 =np.arange(12).reshape(4,3) # 4 rows and 3 column

a1.shape # 12 rows , o column
for i in a1:
  print(i)

for i in a2: # Rowwsie loop
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [ ]:
print(a2)
for i in np.nditer(a2):
  print(i)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


#### Indexing and Slicing

In [17]:
a1 =np.arange(10,31)
a2 =np.arange(36).reshape(6,6) # 4 rows and 3 column
a3 = np.arange(48).reshape(4,4,3)

### a[ :  : ] means ALL ROWS and ALL COLUMNS
print('1D Array')
print(a1[5]) # item at 5th position , counting starts with zero
print(a1[5 : 10]) # Range i.e. item from 5th to 7th
print(a1[3 : 18 : 3]) # every 3 item
print(a1[::])

print('2D Array')
print(a2[3])			#3rd row , counting starts with zero
print(a2[1 : 6]) 		# Range (1-6) of rows
print(a2[1 : 6 : 2])	# Range(1-6) of rows with interval(2) and all columns
print(a2[:, 2:6:3])   # Range(2-4) of column with interval(3) and all rows
print(a2[1 : 6 : 2, 2 : 6 : 3 ]) #rows(1-6)with interval 2 and columns(2-6) with intreval 3
print(a2[::, ::]) 		# all rows and all columns

print('3D Array')
print(a3[2]) # 2nd row od 3D array, counting starts with zero
print(a3[1 : 3]) # Range of rows i.e. rows from 1st to 3rd
print(a3[ :  :3]) # all row all column and every 3rd item
print('-----')
##pick one item in 3D array
a3[::, ::, ::] # all from 3d , all from inner adn all column
print(a3[1,2,0]) # 1st row of 3D array, 2nd row of inner array zero colu
print(a3[1:4:2, ::]) # In 3D array, rows from 1 to 4,interval is 2
print(a3[1:4:2, 1:3:2]) # In 3D array, rows from 1 to 4,interval is 2, Also from inner array rows 1 to 3 and interval 2
print('-----')
print(a3[1:4:2, 1:3:2, 0:2:2])# In 3D array, rows from 1 to 4,interval is 2, Also from inner array rows 1 to 3 and interval 2, col from 0 to 2 with interval 2


1D Array
15
[15 16 17 18 19]
[13 16 19 22 25]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
2D Array
[18 19 20 21 22 23]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [30 31 32 33 34 35]]
[[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]
 [26 29]
 [32 35]]
[[ 8 11]
 [20 23]
 [32 35]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
3D Array
[[24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]
[[[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
-----
18
[[[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
[[[15 16 17]]

 [[39 40 41]]]
-----
[[[15]]

 [[39]]]


#### Stacking

In [ ]:
# Shape of array need to be SAME
  a1 =np.arange(9).reshape(3,3)
  a2 =np.arange(9).reshape(3,3)

a3 = np.hstack((a1,a2)) # Horizontal stack
a4 = np.vstack((a1,a2)) # Vertical stack

print(a3.shape)
print(a4.shape)

(3, 6)
(6, 3)


####Splitting

In [ ]:
# Opposit of stacking and equal split must be possible

a =np.arange(36).reshape(6,6)
a1,a2 = np.hsplit(a,2) # horizontally divide in 2 part
a3,a4,a4 = np.vsplit(a,3) # virtically divide in 2 part

print(a1.shape)
print(a3.shape)


(6, 3)
(2, 6)


#### Broadcasting

In [ ]:
# same shape i.e. overlap
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print("---")
print(b)
print("---")
print(a+b)

[[0 1 2]
 [3 4 5]]
---
[[ 6  7  8]
 [ 9 10 11]]
---
[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shape then atleast one dimesion should match and other need to be 1 for smaller array
a = np.arange(6).reshape(3,2) # 3 rows
b = np.arange(3).reshape(3,1) # 3 rows

print(a)
print("---")
print(b)
print("---")
print(a+b)

print("****")
a = np.arange(8).reshape(2,4) # 3 col
b = np.arange(4).reshape(1,4) # 3 col

print(a)
print("---")
print(b)
print("---")
print(a+b)

[[0 1]
 [2 3]
 [4 5]]
---
[[0]
 [1]
 [2]]
---
[[0 1]
 [3 4]
 [6 7]]
****
[[0 1 2 3]
 [4 5 6 7]]
---
[[0 1 2 3]]
---
[[ 0  2  4  6]
 [ 4  6  8 10]]


#### Handling missing values

In [20]:
a = np.array([1,2,3,np.nan,4,6,np.nan,8]).reshape(2,4)
print(a)

[[ 1.  2.  3. nan]
 [ 4.  6. nan  8.]]


In [22]:
# null values
np.isnan(a) # boolean o/p
a[np.isnan(a)] # fetch nan
# print(isnan)

array([nan, nan])

In [23]:
# fetch not null values

a[~np.isnan(a)]

array([1., 2., 3., 4., 6., 8.])

In [26]:
# Repalce nan
b=np.nan_to_num(a, nan=11)

a[np.isnan(a)] = 0 # change in main array
print(a.shape)
print(a)

(2, 4)
[[1. 2. 3. 0.]
 [4. 6. 0. 8.]]


#### Analytical

In [28]:
a = np.random.randint(1,20,12)
b = np.random.randint(1,20,12).reshape(3,4)



##### sort vs sorted

In [ ]:
# sort() is numpy function o/p is np
# sorted is Python function o/p is list
# Row - > axis =1
# Col - > axis =0

np.sort(a)#[::-1] # o/p is COPY of sorted array
np.sort(b, axis= 0) # by default row wise sort

np.sort(a)[::-1] # Reverse the sort
np.sort(b, axis= 0)[::-1]

sorted(a) # o/p is list


[np.int64(8),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(11),
 np.int64(12),
 np.int64(12),
 np.int64(15),
 np.int64(18),
 np.int64(18),
 np.int64(19),
 np.int64(19)]

##### append

In [ ]:
np.append(a,200) # add value at the end

array([  4,   1,  14,  19,   8,  13,   1,  13,  10,   8,   9,   6, 200])

In [ ]:
np.append(b, 100) # withoit axis , 2D will become 1D and then added

np.append(b,np.random.random((b.shape[0],1)),axis= 1) # use broadcasting 1


array([[ 3.        , 13.        ,  1.        , 12.        ,  0.44361747],
       [15.        , 14.        , 15.        , 14.        ,  0.49271607],
       [12.        ,  3.        , 10.        ,  6.        ,  0.32052878]])

#####unique

In [ ]:
list=[1,2,2,4,1,2,2,3,4]
c=np.array(list)
np.unique(c)

array([1, 2, 3, 4])

#####expand_dims - adds a new axis (dimension) to an array at the specified axis position.

In [ ]:
np.expand_dims(a,axis=0).shape
np.expand_dims(a,axis=1).shape

(12, 1)

In [ ]:
np.expand_dims(b,axis=0).shape
np.expand_dims(b,axis=1).shape
np.expand_dims(b,axis=2).shape

(3, 4, 1)

#####np.where(condition) -  indices where the condition is True.

In [29]:
#np.where(condition, x, y)
np.where(b > 10, b, -1)

# np.where(a > 8, 1, 0)

array([[-1, -1, -1, -1],
       [18, 18, 18, -1],
       [17, -1, -1, 12]])

#####np.isin

In [ ]:
# to check if a list of item is found in array
items = [1,2,3,5,7,8,9]
a[np.isin(a,items)]

array([8, 3, 7, 7])